// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9CgmRqOJV3WigkEfnPqh-4T_HkRwnE9A',
    appId: '1:842618308728:web:c187bb7a69c23130d7858d',
    messagingSenderId: '842618308728',
    projectId: 'hungro-50299',
    authDomain: 'hungro-50299.firebaseapp.com',
    storageBucket: 'hungro-50299.appspot.com',
    measurementId: 'G-Z43R10BCNY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZogBTxzjnG8OcZLhCWSp2abHkUIqGs6k',
    appId: '1:842618308728:android:c493ec21132b858bd7858d',
    messagingSenderId: '842618308728',
    projectId: 'hungro-50299',
    storageBucket: 'hungro-50299.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkYputgusqFyWoxFzifW8iwCRru6paGuU',
    appId: '1:842618308728:ios:b2fab6f4cd1cf893d7858d',
    messagingSenderId: '842618308728',
    projectId: 'hungro-50299',
    storageBucket: 'hungro-50299.appspot.com',
    iosBundleId: 'com.mrcodefrost.hungroFoodDelivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkYputgusqFyWoxFzifW8iwCRru6paGuU',
    appId: '1:842618308728:ios:6955f74dc890981ed7858d',
    messagingSenderId: '842618308728',
    projectId: 'hungro-50299',
    storageBucket: 'hungro-50299.appspot.com',
    iosBundleId: 'com.mrcodefrost.hungroFoodDelivery.RunnerTests',
  );
}
